[caches.default]
type = "fs"

[caches.fs_current_dir]
type = "fs"
cache_dir = ".detcache"

[caches.s3_us_east_1]
type = "s3"
bucket = "detcache-example"
region = "us-east-1"
# Optional settings:
prefix_key = "foo/bar"
profile = "detcache-example-foo-bar-rw"
